### ISSUE TITLE
Unexpected var in "for (var line of readlines...)"

### ISSUE THREAD

**Issue by shakthimaan** [neurosnap/gen-readlines#10]
The following code works fine:

```
  for (var line of readlines(fd, stats.size)) {
    yield line.toString(); 
  }
```

When using eslint on the above code, the following errors are emitted:

```
/path/to/code.js
  26:8  error  All 'var' declarations must be at the top of the function scope  vars-on-top
  26:8  error  Unexpected var, use let or const instead                         no-var

✖ 2 problems (2 errors, 0 warnings)
```

Is there an alternate syntax to using "for (var line of ...)"?

**Comment by neurosnap** [comment]
The alternate syntax would be `for (const line of ...)`

**Comment by shakthimaan** [comment]
Using 'for (const line of ...)' does not loop through the entries. 

After 'line' gets initialized with the first entry from the file, for every iteration, 'line' retains its value.

**Comment by neurosnap** [comment]
> After 'line' gets initialized with the first entry from the file, for every iteration, 'line' retains its value.

`let` and `const` are block-scoped, so `line` gets re-assigned on every iteration.  

> You can use const instead of let too, if you don't modify the variable inside the block.
> https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of

However, depending on the `node` version you are using, `for (const line of ...)` might through an `SyntaxError: Unexpected identifier`, even with `--harmony` flag and `use strict`.

Using `let` instead should work for all versions.  I've added `eslint` to this project, updated the tests to use `let` instead of `var`, and also added more versions of node to travis.

**Comment by neurosnap** [comment]
I forgot to mention, thank you so much for addressing this issue with `gen-readlines`.  Your feedback prompted me to makes some necessary changes to the project.

THANKS!
